### ISSUE TITLE
the scan does not work 

### ISSUE THREAD

**Issue by Migguuel** [PikaBotz/Anya-pika-MD-v2#20]
There has always been a problem with the scan, I have scanned the code more than 5 times and I still have not received the session 
I would like you to solve this problem

**Comment by PikaBotz** [comment]
> There has always been a problem with the scan, I have scanned the code more than 5 times and I still have not received the session I would like you to solve this problem

Reply: Sure bro I'll check the qr session

**Comment by teamolduser** [comment]
> There has always been a problem with the scan, I have scanned the code more than 5 times and I still have not received the session I would like you to solve this problem

Try with real number and original WhatsApp you can get original WhatsApp from play store

**Comment by teamriders098** [comment]
@PikaBotz kidhar mar gaya be gulu gulu mat

**Comment by teamriders098** [comment]
Close kar

**Comment by PikaBotz** [comment]
Nom nom
